import { useMemo } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import type { JournalEntryType } from "../types/domain";
import { TOKENS, colorById } from "../theme/tokens";
import { usePlanner } from "../context/PlannerContext";
import { AppScreen } from "../components/layout/AppScreen";
import { ScreenTitle } from "../components/common/ScreenTitle";
import { SegmentedSwitch } from "../components/common/SegmentedSwitch";
import { FilterChip } from "../components/common/FilterChip";
import { SurfaceCard } from "../components/common/SurfaceCard";
import { EmptyState } from "../components/common/EmptyState";
import { AppButton } from "../components/common/AppButton";

const JOURNAL_TYPE_LABEL: Record<JournalEntryType, string> = {
  transport: "교통",
  stay: "숙소",
  todo: "즐길거리",
  shopping: "쇼핑",
  food: "음식",
  etc: "기타"
};

const JOURNAL_TYPES: Array<JournalEntryType | "all"> = [
  "all",
  "transport",
  "stay",
  "todo",
  "shopping",
  "food",
  "etc"
];

export function JournalScreen() {
  const {
    plans,
    journals,
    settings,
    journalViewMode,
    setJournalViewMode,
    selectedJournalPlanId,
    setSelectedJournalPlanId,
    selectedJournalType,
    setSelectedJournalType,
    setGalleryPermissionState
  } = usePlanner();

  const filteredJournals = useMemo(() => {
    if (journalViewMode === "plan") {
      if (!selectedJournalPlanId) {
        return [];
      }
      return journals.filter((journal) => journal.planId === selectedJournalPlanId);
    }

    if (selectedJournalType === "all") {
      return journals;
    }

    return journals.filter((journal) => journal.type === selectedJournalType);
  }, [journals, journalViewMode, selectedJournalPlanId, selectedJournalType]);

  return (
    <AppScreen>
      <View style={styles.header}>
        <ScreenTitle title="일지" subtitle="하루에 하나씩 자동 생성 · 수정 가능" />
      </View>

      <View style={styles.modeRow}>
        <SegmentedSwitch
          value={journalViewMode}
          onChange={setJournalViewMode}
          options={[
            { label: "일정별 모아보기", value: "plan" },
            { label: "유형별 모아보기", value: "type" }
          ]}
        />
      </View>

      {settings.galleryPermissionState === "denied" ? (
        <SurfaceCard style={styles.permissionWarning}>
          <Text style={styles.permissionText}>갤러리에 접근해야 일지를 만들 수 있어요</Text>
          <View style={styles.permissionActionWrap}>
            <AppButton label="갤러리 권한 승인하기" variant="warning" onPress={() => setGalleryPermissionState("granted")} />
          </View>
        </SurfaceCard>
      ) : null}

      <ScrollView contentContainerStyle={styles.content}>
        {journalViewMode === "plan" ? (
          <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filterRow}>
            {plans.map((plan) => (
              <FilterChip
                key={plan.id}
                label={plan.title}
                dotColor={colorById(plan.colorId)}
                active={selectedJournalPlanId === plan.id}
                onPress={() => setSelectedJournalPlanId(plan.id)}
              />
            ))}
          </ScrollView>
        ) : (
          <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filterRow}>
            {JOURNAL_TYPES.map((type) => (
              <FilterChip
                key={type}
                label={type === "all" ? "전체" : JOURNAL_TYPE_LABEL[type]}
                active={selectedJournalType === type}
                onPress={() => setSelectedJournalType(type)}
              />
            ))}
          </ScrollView>
        )}

        {filteredJournals.length === 0 ? (
          <EmptyState message="정보가 부족해 일지를 만들지 못 했어요" />
        ) : (
          filteredJournals.map((journal) => (
            <SurfaceCard key={journal.id} style={styles.journalCard}>
              <View style={styles.journalImageArea}>
                <Ionicons name="image-outline" size={20} color={TOKENS.color.inkSoft} />
                <Text style={styles.journalImageText}>{journal.imageUri ? "사진 연결" : "사진 없음"}</Text>
              </View>

              <View style={styles.journalBody}>
                <View style={styles.journalHeaderRow}>
                  <Text style={styles.journalDate}>{journal.dateLocal.replace(/-/g, ".")}</Text>
                  <Text style={styles.journalType}>{JOURNAL_TYPE_LABEL[journal.type]}</Text>
                </View>
                <Text style={styles.journalText}>{journal.text}</Text>

                <View style={styles.journalFooterRow}>
                  <Text style={styles.journalTag}>{journal.autoGenerated ? "자동" : "수동"}</Text>
                  <View style={styles.journalActions}>
                    <AppButton label="수정" variant="secondary" onPress={() => {}} style={styles.actionButton} />
                    <AppButton label="삭제" variant="secondary" onPress={() => {}} style={styles.actionButton} />
                  </View>
                </View>
              </View>
            </SurfaceCard>
          ))
        )}
      </ScrollView>
    </AppScreen>
  );
}

const styles = StyleSheet.create({
  header: {
    paddingTop: TOKENS.space.sm,
    paddingHorizontal: TOKENS.space.lg,
    paddingBottom: TOKENS.space.sm
  },
  modeRow: {
    paddingHorizontal: TOKENS.space.lg
  },
  permissionWarning: {
    marginHorizontal: TOKENS.space.lg,
    marginTop: TOKENS.space.sm,
    borderColor: "#D9A36A",
    backgroundColor: "#FEEED9",
    padding: TOKENS.space.md,
    gap: TOKENS.space.sm
  },
  permissionText: {
    fontFamily: TOKENS.font.body,
    color: TOKENS.color.warning,
    fontSize: 13
  },
  permissionActionWrap: {
    alignSelf: "flex-start"
  },
  content: {
    paddingVertical: TOKENS.space.md,
    paddingHorizontal: TOKENS.space.lg,
    gap: TOKENS.space.sm,
    paddingBottom: 120
  },
  filterRow: {
    gap: TOKENS.space.xs,
    paddingBottom: TOKENS.space.sm
  },
  journalCard: {
    overflow: "hidden"
  },
  journalImageArea: {
    height: 88,
    borderBottomColor: TOKENS.color.line,
    borderBottomWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: TOKENS.color.bgMuted
  },
  journalImageText: {
    marginTop: 4,
    fontFamily: TOKENS.font.body,
    color: TOKENS.color.inkSoft,
    fontSize: 11
  },
  journalBody: {
    padding: TOKENS.space.md,
    gap: TOKENS.space.sm
  },
  journalHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center"
  },
  journalDate: {
    fontFamily: TOKENS.font.bold,
    fontSize: 13,
    color: TOKENS.color.ink
  },
  journalType: {
    fontFamily: TOKENS.font.medium,
    color: TOKENS.color.accentDeep,
    fontSize: 11
  },
  journalText: {
    fontFamily: TOKENS.font.body,
    color: TOKENS.color.ink,
    fontSize: 13,
    lineHeight: 20
  },
  journalFooterRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center"
  },
  journalTag: {
    fontFamily: TOKENS.font.medium,
    color: TOKENS.color.inkSoft,
    fontSize: 11
  },
  journalActions: {
    flexDirection: "row",
    gap: TOKENS.space.xs
  },
  actionButton: {
    paddingVertical: 6,
    minWidth: 52
  }
});
