const test = require("node:test");
const assert = require("node:assert/strict");

const { rebuildAutoJournals } = require("../src/journal/autoJournal.ts");
const { composeJournalDraft } = require("../src/journal/generator.ts");

const plans = [
  {
    id: "plan-a",
    title: "오사카 여행",
    destination: "오사카",
    startDateLocal: "2026-04-09",
    endDateLocal: "2026-04-16",
    isForeign: true,
    journalEnabledAtMs: 1700000000000,
    updatedAtMs: 1,
    colorId: 2
  }
];

const eventsByPlan = {
  "plan-a": [
    {
      id: "e1",
      planId: "plan-a",
      title: "난바 체크인",
      dateLocal: "2026-04-10",
      startTimeLocal: "15:00",
      category: "stay",
      status: "confirmed",
      locationLabel: "난바",
      colorId: 2
    },
    {
      id: "e2",
      planId: "plan-a",
      title: "도톤보리 저녁",
      dateLocal: "2026-04-10",
      startTimeLocal: "19:00",
      category: "food",
      status: "completed",
      locationLabel: "도톤보리",
      colorId: 4
    }
  ]
};

test("rebuildAutoJournals preserves manual entries and refreshes auto entries", () => {
  const current = [
    {
      id: "manual-1",
      planId: "plan-a",
      dateLocal: "2026-04-11",
      type: "food",
      text: "수동 메모",
      imageUri: null,
      autoGenerated: false
    }
  ];

  const next = rebuildAutoJournals(plans, eventsByPlan, current, true, composeJournalDraft);
  assert.equal(next.some((entry) => entry.id === "manual-1"), true);
  assert.equal(next.some((entry) => entry.id === "jr-auto-plan-a-2026-04-10"), true);
});

test("rebuildAutoJournals skips plans not enabled in journal tab", () => {
  const disabledPlans = [
    {
      ...plans[0],
      id: "plan-disabled",
      journalEnabledAtMs: null
    }
  ];
  const disabledEventsByPlan = {
    "plan-disabled": eventsByPlan["plan-a"].map((event) => ({ ...event, planId: "plan-disabled" }))
  };

  const next = rebuildAutoJournals(disabledPlans, disabledEventsByPlan, [], true, composeJournalDraft);
  assert.equal(next.length, 0);
});
