const test = require("node:test");
const assert = require("node:assert/strict");

const {
  applyJournalTextUpdate,
  applyJournalDelete
} = require("../src/journal/journalActions.ts");

const BASE_ENTRY = {
  id: "jr-1",
  planId: "plan-a",
  dateLocal: "2026-03-01",
  type: "food",
  text: "기존 텍스트",
  imageUri: null,
  autoGenerated: true
};

test("applyJournalTextUpdate updates target entry text with trimmed value", () => {
  const next = applyJournalTextUpdate([BASE_ENTRY], "jr-1", "  수정된 텍스트  ");
  assert.equal(next[0].text, "수정된 텍스트");
});

test("applyJournalTextUpdate ignores blank input", () => {
  const next = applyJournalTextUpdate([BASE_ENTRY], "jr-1", "   ");
  assert.equal(next[0].text, "기존 텍스트");
});

test("applyJournalDelete removes target entry", () => {
  const entries = [BASE_ENTRY, { ...BASE_ENTRY, id: "jr-2" }];
  const next = applyJournalDelete(entries, "jr-1");
  assert.deepEqual(next.map((entry) => entry.id), ["jr-2"]);
});
