const test = require("node:test");
const assert = require("node:assert/strict");

const {
  moveJournalToTrash,
  restoreJournalFromTrash,
  restoreEntityFromTrash
} = require("../src/journal/trashFlow.ts");

const JOURNAL = {
  id: "jr-1",
  planId: "plan-a",
  dateLocal: "2026-04-10",
  type: "food",
  text: "본문",
  imageUri: null,
  autoGenerated: true
};

test("moveJournalToTrash removes journal and creates trash snapshot", () => {
  const nowMs = 1700000000000;
  const next = moveJournalToTrash([JOURNAL], [], "jr-1", nowMs);

  assert.equal(next.journals.length, 0);
  assert.equal(next.trashItems.length, 1);
  assert.equal(next.trashItems[0].entityType, "journalEntry");
  assert.equal(next.trashItems[0].snapshotJournal.id, "jr-1");
});

test("restoreJournalFromTrash restores journal entry and removes trash item", () => {
  const nowMs = 1700000000000;
  const deleted = moveJournalToTrash([JOURNAL], [], "jr-1", nowMs);
  const restored = restoreJournalFromTrash(deleted.journals, deleted.trashItems, deleted.trashItems[0].id);

  assert.equal(restored.trashItems.length, 0);
  assert.equal(restored.journals.length, 1);
  assert.equal(restored.journals[0].id, "jr-1");
});

test("restoreEntityFromTrash restores event snapshots for non-journal entities", () => {
  const restored = restoreEntityFromTrash(
    {
      journals: [],
      eventsByPlan: { "plan-a": [] },
      dayMemosByPlan: { "plan-a": [] },
      plans: []
    },
    [
      {
        id: "tr-ev-1",
        planId: "plan-a",
        entityType: "event",
        title: "한강 자전거",
        deletedAtMs: 1700000000000,
        purgeAtMs: 1700000000000 + 1,
        snapshotEvent: {
          id: "ev-1",
          planId: "plan-a",
          title: "한강 자전거",
          dateLocal: "2026-03-02",
          category: "todo",
          status: "confirmed",
          colorId: 2
        }
      }
    ],
    "tr-ev-1"
  );

  assert.equal(restored.trashItems.length, 0);
  assert.equal(restored.eventsByPlan["plan-a"].length, 1);
  assert.equal(restored.eventsByPlan["plan-a"][0].id, "ev-1");
});
