export type EventStatus = "temporary" | "confirmed" | "completed" | null;
export type EventCategory = "transport" | "stay" | "todo" | "shopping" | "food" | "etc" | null;

export interface TravelPlan {
  id: string;
  title: string;
  destination: string;
  startDateLocal: string;
  endDateLocal: string;
  isForeign: boolean;
  updatedAtMs: number;
  colorId: number;
}

export interface ChangeProposalPreview {
  summary: string;
  operations: string[];
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  text: string;
  createdAtMs: number;
  imageUris: string[];
  proposal?: ChangeProposalPreview;
}

export interface TripEvent {
  id: string;
  planId: string;
  title: string;
  dateLocal: string;
  startTimeLocal?: string;
  endTimeLocal?: string;
  category: EventCategory;
  status: EventStatus;
  memo?: string;
  colorId: number;
}

export interface DayMemo {
  planId: string;
  dateLocal: string;
  memo: string;
}

export type JournalEntryType = "transport" | "stay" | "todo" | "shopping" | "food" | "etc";

export interface JournalEntry {
  id: string;
  planId: string;
  dateLocal: string;
  type: JournalEntryType;
  text: string;
  imageUri: string | null;
  autoGenerated: boolean;
}

export interface TrashItem {
  id: string;
  planId: string;
  entityType: "plan" | "event" | "dayMemo" | "journalDay" | "journalEntry";
  title: string;
  deletedAtMs: number;
  purgeAtMs: number;
}

export interface UserSettings {
  journalGenerateWithoutData: boolean;
  galleryPermissionState: "unknown" | "granted" | "denied" | "limited";
}
