export type EventStatus = "temporary" | "confirmed" | "completed" | null;
export type EventCategory = "transport" | "stay" | "todo" | "shopping" | "food" | "etc" | null;

export interface TravelPlan {
  id: string;
  title: string;
  destination: string;
  startDateLocal: string;
  endDateLocal: string;
  isForeign: boolean;
  journalEnabledAtMs: number | null;
  updatedAtMs: number;
  colorId: number;
}

export interface ChangeProposalPreview {
  summary: string;
  operations: string[];
  operationPayloads: ProposalOperationPayload[];
  source?: "chat" | "ocr";
  confidence?: number;
  state?: "pending" | "registered" | "edited" | "cancelled";
}

export interface ProposalOperationPayload {
  action: "create" | "update" | "delete";
  targetEventId?: string;
  draft: Partial<TripEvent>;
  enabled?: boolean;
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant" | "system";
  text: string;
  createdAtMs: number;
  imageUris: string[];
  proposal?: ChangeProposalPreview;
}

export interface TripEvent {
  id: string;
  planId: string;
  title: string;
  dateLocal: string;
  startTimeLocal?: string;
  endTimeLocal?: string;
  departAtLocal?: string;
  departTimezone?: string;
  arriveAtLocal?: string;
  arriveTimezone?: string;
  locationLabel?: string;
  category: EventCategory;
  status: EventStatus;
  memo?: string;
  colorId: number;
}

export interface DayMemo {
  planId: string;
  dateLocal: string;
  memo: string;
}

export type JournalEntryType = "transport" | "stay" | "todo" | "shopping" | "food" | "etc";

export interface JournalEntry {
  id: string;
  planId: string;
  dateLocal: string;
  type: JournalEntryType;
  text: string;
  imageUri: string | null;
  autoGenerated: boolean;
}

export interface TrashItem {
  id: string;
  planId: string;
  entityType: "plan" | "event" | "dayMemo" | "journalDay" | "journalEntry";
  title: string;
  deletedAtMs: number;
  purgeAtMs: number;
  snapshotPlan?: TravelPlan;
  snapshotEvent?: TripEvent;
  snapshotDayMemo?: DayMemo;
  snapshotJournal?: JournalEntry;
}

export interface UserSettings {
  journalGenerateWithoutData: boolean;
  galleryPermissionState: "unknown" | "granted" | "denied" | "limited";
}
