import type {
  ChatMessage,
  DayMemo,
  JournalEntry,
  TravelPlan,
  TrashItem,
  TripEvent,
  UserSettings
} from "../types/domain";

const now = Date.now();

export const seedPlans: TravelPlan[] = [
  {
    id: "plan-seoul-food",
    title: "서울 미식 투어",
    destination: "서울",
    startDateLocal: "2026-03-01",
    endDateLocal: "2026-03-04",
    isForeign: false,
    journalEnabledAtMs: null,
    updatedAtMs: now - 30_000,
    colorId: 0
  },
  {
    id: "plan-japan-osaka",
    title: "오사카 벚꽃 여행",
    destination: "오사카",
    startDateLocal: "2026-04-09",
    endDateLocal: "2026-04-16",
    isForeign: true,
    journalEnabledAtMs: now - 600_000,
    updatedAtMs: now - 600_000,
    colorId: 2
  },
  {
    id: "plan-workshop-busan",
    title: "부산 워크샵",
    destination: "부산",
    startDateLocal: "2026-05-20",
    endDateLocal: "2026-05-22",
    isForeign: false,
    journalEnabledAtMs: null,
    updatedAtMs: now - 4_200_000,
    colorId: 5
  }
];

export const seedMessages: Record<string, ChatMessage[]> = {
  "plan-seoul-food": [
    {
      id: "m1",
      role: "assistant",
      text: "3월 1일 저녁에 성수동 맛집 코스를 먼저 배치해둘게요.",
      createdAtMs: now - 240_000,
      imageUris: []
    },
    {
      id: "m2",
      role: "assistant",
      text: "스크린샷 OCR 결과로 이벤트 3개 초안을 만들었어요.",
      createdAtMs: now - 180_000,
      imageUris: [],
      proposal: {
        summary: "3개 이벤트 초안",
        operations: ["등록 2건", "수정 1건", "취소 0건"],
        operationPayloads: [
          {
            action: "create",
            draft: {
              title: "도톤보리 저녁",
              dateLocal: "2026-04-10",
              startTimeLocal: "18:30",
              status: "confirmed"
            }
          }
        ],
        source: "ocr",
        confidence: 0.86,
        state: "pending"
      }
    }
  ],
  "plan-japan-osaka": [
    {
      id: "m3",
      role: "assistant",
      text: "간사이 공항 도착 후 난바 이동, 저녁 체크인 일정이 연결되어 있어요.",
      createdAtMs: now - 720_000,
      imageUris: []
    }
  ],
  "plan-workshop-busan": []
};

export const seedEvents: Record<string, TripEvent[]> = {
  "plan-seoul-food": [
    {
      id: "e1",
      planId: "plan-seoul-food",
      title: "광장시장 아침 식사",
      dateLocal: "2026-03-01",
      startTimeLocal: "08:30",
      category: "food",
      status: "confirmed",
      memo: "빈대떡, 육회",
      colorId: 0
    },
    {
      id: "e2",
      planId: "plan-seoul-food",
      title: "북촌 산책",
      dateLocal: "2026-03-01",
      startTimeLocal: "11:00",
      category: "todo",
      status: "confirmed",
      colorId: 3
    },
    {
      id: "e3",
      planId: "plan-seoul-food",
      title: "성수 카페",
      dateLocal: "2026-03-01",
      startTimeLocal: "15:00",
      category: "food",
      status: null,
      colorId: 4
    },
    {
      id: "e4",
      planId: "plan-seoul-food",
      title: "남산 야경",
      dateLocal: "2026-03-01",
      startTimeLocal: "20:00",
      category: "todo",
      status: "completed",
      colorId: 1
    },
    {
      id: "e5",
      planId: "plan-seoul-food",
      title: "한남 쇼핑",
      dateLocal: "2026-03-02",
      category: "shopping",
      status: "confirmed",
      colorId: 6
    }
  ],
  "plan-japan-osaka": [
    {
      id: "j1",
      planId: "plan-japan-osaka",
      title: "인천공항 출발",
      dateLocal: "2026-04-09",
      startTimeLocal: "09:40",
      category: "transport",
      status: "confirmed",
      departAtLocal: "2026-04-09T09:40",
      departTimezone: "Asia/Seoul",
      arriveAtLocal: "2026-04-09T11:20",
      arriveTimezone: "Asia/Tokyo",
      colorId: 2
    },
    {
      id: "j2",
      planId: "plan-japan-osaka",
      title: "도톤보리 체크리스트",
      dateLocal: "2026-04-10",
      category: "todo",
      status: null,
      colorId: 7
    },
    {
      id: "j3",
      planId: "plan-japan-osaka",
      title: "우메다 숙소 체크인",
      dateLocal: "2026-04-10",
      category: "stay",
      status: "confirmed",
      colorId: 2
    }
  ],
  "plan-workshop-busan": []
};

export const seedDayMemos: Record<string, DayMemo[]> = {
  "plan-seoul-food": [
    { planId: "plan-seoul-food", dateLocal: "2026-03-01", memo: "저녁은 예약 필요" },
    { planId: "plan-seoul-food", dateLocal: "2026-03-02", memo: "쇼핑 후 택배 가능 여부 확인" }
  ],
  "plan-japan-osaka": [
    { planId: "plan-japan-osaka", dateLocal: "2026-04-10", memo: "USJ 익스프레스 여부 확인" }
  ],
  "plan-workshop-busan": []
};

export const seedJournals: JournalEntry[] = [
  {
    id: "jr-1",
    planId: "plan-seoul-food",
    dateLocal: "2026-03-01",
    type: "food",
    text: "광장시장에서 시작해 성수, 남산까지 이어진 하루였어요. 이동 동선이 짧아 여유가 있었습니다.",
    imageUri: null,
    autoGenerated: true
  },
  {
    id: "jr-2",
    planId: "plan-japan-osaka",
    dateLocal: "2026-04-10",
    type: "stay",
    text: "난바에서 우메다로 넘어와 체크인을 마쳤고, 저녁엔 도톤보리에서 동선을 가볍게 점검했어요.",
    imageUri: null,
    autoGenerated: true
  },
  {
    id: "jr-3",
    planId: "plan-japan-osaka",
    dateLocal: "2026-04-11",
    type: "food",
    text: "수동으로 추가한 기록: 타코야키 집 대기시간이 길어 대체 매장으로 변경함.",
    imageUri: null,
    autoGenerated: false
  }
];

export const seedTrash: TrashItem[] = [
  {
    id: "tr-1",
    planId: "plan-seoul-food",
    entityType: "event",
    title: "한강 자전거",
    deletedAtMs: now - 86_400_000,
    purgeAtMs: now + 29 * 86_400_000,
    snapshotEvent: {
      id: "tr-1-event",
      planId: "plan-seoul-food",
      title: "한강 자전거",
      dateLocal: "2026-03-02",
      category: "todo",
      status: "confirmed",
      colorId: 3
    }
  }
];

export const seedSettings: UserSettings = {
  journalGenerateWithoutData: true,
  galleryPermissionState: "granted"
};
